// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    C1: typeof import('./src/components/C1.vue')['default']
    Drag: typeof import('./src/components/Drag.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    UseDraggable: typeof import('@vueuse/components')['UseDraggable']
  }
}

export { }
